apiVersion: v1
kind: ConfigMap
metadata:
  name: dilane-shop-config
  namespace: dilane-shop
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,dilane-shop.local"
  DJANGO_LOG_LEVEL: "INFO"
  DB_ENGINE: "postgres"
  DB_NAME: "ecommerce"
  DB_USER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_CONN_MAX_AGE: "60"
  DB_SSLMODE: "disable"
  TAX_RATE_PERCENT: "20"
