apiVersion: v1
kind: Secret
metadata:
    name: dilane-shop-secrets
    namespace: dilane-shop
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:cHKWTzK0ytm3elYCZWX0NOLaMLkOdwYyzWEuLk8AX/ReqoIcjfm4j2HWWjctlEPI6+OoGR6pgmSG7gKeMNZu2zh/1g==,iv:iggjxOfAlP7r8e+wewsTM5WK45wVlAke+EtHk7xgWfI=,tag:xsGaOxRAKUUf9XaNfLCxxw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:cxFY3g5vNYSmRwMc4zbz6fEvxQMMZj7JkSxPhz5wkqU=,iv:/FnTPgq18VFLACkMt4V610v84Ir1fDHAE5EFPoXmd0s=,tag:FOHalfb/95XjCvtMzNpEuA==,type:str]
    STRIPE_PUBLIC_KEY: ENC[AES256_GCM,data:mr1Las+rXPSRUQqjraRFp3u0pg==,iv:j5kig+qDuvXAnBXUkRzaaBavOd5Lazi2cj34KDYYVUo=,tag:fVigywM3HJjeTmp/ARB6cQ==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:E1wmH6Cyx1H8RMbUMD6eXeK9zw==,iv:QiurVcxrZhp0+wFeSfxzvcHHSc/9QFkuJNc2hn5WwmY=,tag:COLSSV4tnaI44oPpAKoG9A==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:wg+KvSqvMbGzZYIlaEqQ0cc=,iv:90dR8Rm7WG6PytDDWo2iK9O54+YuSGAq5A0yVeq8elU=,tag:w8CBuVg6p/B4Oi9CkYRW9w==,type:str]
    BREVO_SMTP_LOGIN: ENC[AES256_GCM,data:krxSbQDtHCFMxzO9Oo5Q7FdKsZS4m2RQ,iv:q0Xb6lmUouGh/6zjXPi49f5VNKgAHJ3Kw+4H4aRlC5w=,tag:c5lKMK47SOXF4e2KKU15sQ==,type:str]
    BREVO_SMTP_KEY: ENC[AES256_GCM,data:1qXNPV65QpwRNqnqwVsZ/rFADMS1/xbvKJHBNZCx0lIhvkYO18BHUL47ClGW5PdvPPZwvgeJMK6Wjh0kwHOyjac44GKkBI9zG8Fi+h+Sztxe+WOC1FF/GyJg,iv:CVdFG+0BzsKka90YAhbUfr4GQGDCpSpR3Va+dQsbLE8=,tag:iaERU3jm3cbp2c2pu6HKCw==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:RmUhKRm/dDfEgaYCEFqy1veOEtiszjX7+g==,iv:eX8rvFbcz7tjPwviMdftEzexwPYRvUwjcPWAwDgtn1c=,tag:9wx0+od/rbImajbBMak9ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQkVzbjlkZmNNaGtDRjk1
            VHBBMDdxbDVHTG5ZVXJCMi9uY25Da0ZkeVJrCkIxek5wRklDVk5NNW9BWkZ3cnhR
            ZURDT0RMUVZKUnJlSnZYSlpCYzdIVjQKLS0tIGFGSlRoSnBRN0V0S0NtOExoYjJO
            RVR0eTdhTHJvVHd2S1gzODBySk9Bc1kKl4W3z26neFd5JP+bqytIeYGNvRbn1WhQ
            vR9Lv8gMmOUMf7x+BxpWjZEuNltQeKEyufZWoTENpU0v82VOZEvvGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18tf4g52kmdt6v67lfql5nr02ypjy9pn0sv0349wsmepn9f2kkfhq36nrqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T10:55:40Z"
    mac: ENC[AES256_GCM,data:9cLiut3NwI+spKiHlCoNyVMDbFcmoPqHykuTh4ZpP1WkH4xZF/bjQlujoXSFts8Mh3gFLKmrf+9dDieZNK//No9GP2tKVawGn9cF8H6ByoEDoExfvSfRPe5K+CSiUe6yYUH+VBUBFMZpLLWWw1FyUJepTVPTcJMZ6Kg/pR6gmv4=,iv:/EZgttNHr8/aBRfPq/qpyBT0hEXap8Eo+0udfhacFG8=,tag:VBLYV5sc0RrYfVPx+beTvw==,type:str]
    version: 3.13.3
