# Generated by Django 6.0.3 on 2026-09-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_commande_stock_deducted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Article de commande', 'verbose_name_plural': 'Articles de commande'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
