apiVersion: v1
kind: Secret
metadata:
    name: dilane-shop-secrets
    namespace: dilane-shop
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:qiCQS8GVd4hXkOtN8rR9xjDEm74K2jN6V4gJMD8Yv/sCFnwQSlKGZxGkdeS/hteqr3XcnakZjQM9XHlK7sU0Fw==,iv:mnnU5BP1XWHppTWpxQM7/zPg0asfNZBQevAy1TMAZI4=,tag:jLihrZDCWfBFfnyzifQenA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:xmj7bXNUkSWjAa4sPtLcH+JdNw7KUbkzy7vPWUe9187oQrs3z9y7OnWv2Z+3Kp7e,iv:W3cjSEQHiHlxjbToy4RJEQdCo9IXMVRIKDq4aM5NMrs=,tag:fMBWKVpnIn0spYMzKdwPeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOUNmZVY5QjhrMk5Wckha
            ZUJZUG1VRVhFV0VNUjI1S1hkRTNSSS9EbWxFCmVOb0F1eS9NSlBYdzRkVW9wRDRQ
            bzRRbnBOOHQ4TkMvTnpsV1h4VFhvUG8KLS0tIFRYck5NTXpiSEVOZWszSTM1OXRi
            c0trd2ptQmlBRVJOaGNsVjdwY2d0NEEKCElVKVsaVzg2i3B3QXTlv0QjCGzQ8IKQ
            //zycBX0/f6HDKE3nHD1MBc0JnNYq2RNLYogWSyxKKKkTXgHDWb8uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18tf4g52kmdt6v67lfql5nr02ypjy9pn0sv0349wsmepn9f2kkfhq36nrqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T19:02:29Z"
    mac: ENC[AES256_GCM,data:DvZa5QPuIscdxTXGQGDvEMZR8dwxC/4kCbxSNk+1PMxfa4IN5d/Z7UgFic94vqOqgWvGhfEbcTN/dv2890C4+1gGRHfxbMxW7PjK9oJHc6bXvclFZSlu2L+07p8vBJFFXFv1NdHmJ8K47gtGnOqI9EozaMain7gRXewRgsumhjs=,iv:gov6ysqElQY7dAxoJIehEvTOYjF0/R8dj5HS8dAKtpk=,tag:7ZjDpTu79i9h2RP05dBvJg==,type:str]
    version: 3.13.3
