apiVersion: v1
kind: Secret
metadata:
    name: dilane-shop-secrets
    namespace: dilane-shop
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:M2QH8xCCbMONkoU/rUmQh2SbtLaDsZTlsCAyLXuz/DH8LzKy3DpaQ4wdFoHj7WB8db6c7nC2yIvGfr3NBKcO+gUn6Q==,iv:IeC9vpBbr6VQdtmevYi03DiJ10gBik+cmNzOy0nZCoU=,tag:AXDnS6WNFQ4bvkNXLFOsJw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:7mjsyVzorFuVnJ8Wed/L++N0VH4EYj7t03/6qrLf1mc=,iv:GmPZzXnqG4dtSo0ZblTqlOs7TDDZkN0mPYAgjwcmovI=,tag:Wi9T9Te4aKmcqwZjDFF5XQ==,type:str]
    STRIPE_PUBLIC_KEY: ENC[AES256_GCM,data:kFf4Imhx/QkhM/nX292fbGbQrSQ4zakw03JTJVM7acdewyE6WkCxk42r0PGK+mgOEBtbsDspkJmVOG1q4y9K6RXAJC7AXo/SY12WLxL3dq64QMArXKNKY5QtuaLniC+h8VvgChnkGOT+voY=,iv:EJ195OF6woDcXBi8nCOjcngFokfhIEXQLU+Gio3Py6I=,tag:9PGkof313sMTiheD6bD5fg==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:kgCAAiBaZ9M2hAmVv/UMFSbS6rOy6wTKSBKZ32SnyPaPrs7LX4M/Vai5EN1V/WPTZeMUZWXtCpDOUPKMYIzL5HuHhGnkQLLJAPNoBCVoaomBdfBIjoLeH2udUf4QyeJA+SDEVvVOEnPJ7bI=,iv:2MLww7gaQ/vNPQvOGns6xg62kTLcA8+ta8kGh60ZctE=,tag:OEDk0F3LXij235aseuKLCA==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:E25z+y361j+ls1HDjV0Vmo4Ci/gUlrlC2irpZQ9+cPMKohiLjIU=,iv:5PNc0s+OZS+5wWrR5xi4iSIU084A+trVKcR0sNsKJ9I=,tag:6aUwwaH8tnMFf23+TAqj/A==,type:str]
    BREVO_SMTP_LOGIN: ENC[AES256_GCM,data:1pJp0jKu74w6N+NOfwQZjWYNUqtFHXKk,iv:UUnrtG4SmrCjmq9b9Ieox/HxYZIj2Opm6kUlpzP7YSU=,tag:003mBKnrNP5tOhQR+lPx7Q==,type:str]
    BREVO_SMTP_KEY: ENC[AES256_GCM,data:s7SsWrZ0xooVPU1QqJWCnWL3kwjzP2bz/5QZR/5yDVJVqEyLGGk5jqx4Pd6YvXoZcWaIq9dsNkUOFke4DEzwZ6KgKKc1sG8xCjGpQe/Khpivd2irdHsck2EU,iv:NfOg/FNqmMq7+AjEIe/TpufmH9W2TApTi92ueWLlqn4=,tag:x4EvkXUk6BTtN01B132PyA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:SZRqsYH/ndBWLxvOfcdbyepvVHBy1JlooQ==,iv:8x4LEYOL0Q2ouIouwXzMD2fnOGZ3854mqYGVlj3PRu0=,tag:bGsxxgTbptyIlzz8TB3Ahg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa2VrL25aVTRaQ1ZYdkRE
            YVY3Sk1pOXBDSEkzMnpPd1NqbzMvcTZqb3prCnExWlJiZXVWZzc0MlZDQmRDbm9j
            MDBRVVZ6ODE0UDFxeUwxdDAvb0JaVzAKLS0tIGQyQWwvT0VicWhiVEZ5Q3hmc3lt
            NUxBUTZUNkRLa0ZFaHlLRkNkOUVCeTgKao2DHQV9JVY4lu8eksajMdRv/ae5o3+0
            gMvgq8swDONcCg+g2edxQ2y8uGnJGFd615gZj+288WOtY80ZraPnsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18tf4g52kmdt6v67lfql5nr02ypjy9pn0sv0349wsmepn9f2kkfhq36nrqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T15:05:16Z"
    mac: ENC[AES256_GCM,data:XzZ64RvJGfPZItSWbshuGx5kiJxh6v06KW/nrSOqKWy2zT7yv7irdr8wNTEaCkhOuALkVAZOYuPckV/ovTCISKC7GnNFLMQj9Ld8Lx3QhBVxwCJs7p3DGEcRGwt/aAcc6W3Cekke7x0FGX+T/2CjvvEkSneuxMAgtGHTFWBxDl4=,iv:GedXI5mUdQeOxx9rmHx0WTczeJoG8w7FT0W1iVi2zX0=,tag:3iCMqLjrebE9yDQs0K4rkA==,type:str]
    version: 3.13.3
